language: node_js
dist: xenial
services:
  - xvfb
node_js:
  - "lts/*"
python:
  - "2.7"
before_install:
  # Override Xenial's default Java version (github.com/travis-ci/travis-ci/issues/10290)
  - export PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
before_script:
  - export PATH="`pwd`/node_modules/.bin:$PATH"
jobs:
  include:
    - name: 'Check'
      script: gulp check
    - name: 'Unit Tests'
      script:
      - gulp unit --coverage
      - ./node_modules/.bin/codecov -f test/coverage/lcov-unit.info
    - name: 'End to End Tests'
      script: gulp e2e --retries=3
branches:
  only:
    - main
addons:
  chrome: stable
cache:
  directories:
    - node_modules
  bundler: true
  yarn: true
