name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci --omit optional

      - name: Check lint & rules
        run: gulp check

      - name: Check types
        run: npx tsc --project tsconfig.json

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: E2E Tests
        run: . ./build_and_run_e2e.sh

      - name: Upload VRT report
        uses: actions/upload-artifact@v3
        with:
          name: vrt-report
          path: |
            .vrt
            vrt-report

  e2e-with-all-experiments-enabled:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: E2E Tests with all experiments enabled
        run: . ./build_and_run_e2e.sh all_experiments_enabled

      - name: Upload VRT report
        uses: actions/upload-artifact@v3
        with:
          name: vrt-report
          path: |
            .vrt
            vrt-report

  binaries:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build binaries
        run: . ./build_binaries.sh

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            dist/*.js
            dist/*.js.map

  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci --omit optional

      - name: Unit Tests
        run: gulp unit --headless --coverage

      - uses: codecov/codecov-action@v3
        with:
          files: ./test/coverage/lcov-unit.info
