name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci --omit optional

      - name: Check
        run: gulp check

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Compile Swgjs with Closure
        run: gulp dist

      - name: E2E Tests
        run: gulp e2e

  e2e-vite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Compile Swgjs Classic with Vite
        run: npx vite build -- --target=classic

      - name: Compile Swgjs Extended Access with Vite
        run: npx vite build -- --target=gaa

      - name: Compile Swgjs Basic with Vite
        run: npx vite build -- --target=basic

      - name: Watch bundle sizes
        uses: jackyef/bundlewatch-gh-action@0.2.1

      - name: E2E Tests
        run: gulp e2e

  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci --omit optional

      - name: Unit Tests
        run: gulp unit --headless --coverage

      - uses: codecov/codecov-action@v3
        with:
          files: ./test/coverage/lcov-unit.info
