name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn --ignore-optional

      - name: Check
        run: gulp check

  e2e-with-closure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn

      - name: Compile JS with Closure
        run: gulp dist

      - name: E2E Tests
        run: gulp e2e

  e2e-with-vite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn

      - name: Compile JS with Vite
        run: npx vite build -- --target=classic

      - name: E2E Tests
        run: gulp e2e

  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn --ignore-optional

      - name: Unit Tests
        run: gulp unit --headless --coverage

      - uses: codecov/codecov-action@v3
        with:
          files: ./test/coverage/lcov-unit.info
