name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci --omit optional

      - name: Check
        run: gulp check

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Compile Swgjs with Closure
        run: gulp dist

      - name: E2E Tests
        run: gulp e2e

  e2e-vite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Compile Swgjs bundles (Classic, Basic, and Extended Access)
        run: npm run build-with-vite-for-ci

      - name: E2E Tests
        run: gulp e2e

  bundle-sizes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Track bundle sizes
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: './dist/*.js'
          build-script: 'build-with-vite-for-ci'

  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci --omit optional

      - name: Unit Tests
        run: gulp unit --headless --coverage

      - uses: codecov/codecov-action@v3
        with:
          files: ./test/coverage/lcov-unit.info
