name: CI

on: [push, pull_request]

jobs:
  check:
    # Canonical will support this LTS until April 2025.
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install the right version of Nodejs
        run: npx n 16

      - name: Install dependencies
        run: yarn

      - name: Check
        run: gulp check

  e2e:
    # Canonical will support this LTS until April 2025.
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install the right version of Nodejs
        run: npx n 16

      - name: Install dependencies
        run: yarn

      - name: E2E Tests
        run: gulp e2e --retries=3

  unit:
    # Canonical will support this LTS until April 2025.
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install the right version of Nodejs
        run: npx n 16

      - name: Install dependencies
        run: yarn

      - name: Unit Tests
        run: gulp unit --headless --coverage

      - uses: codecov/codecov-action@v2
        with:
          file: ./test/coverage/lcov-unit.info
