name: CI

on: [push, pull_request]

jobs:
  check:
    # Canonical will support this LTS until April 2027.
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn --ignore-optional

      - name: Check
        run: gulp check

  e2e:
    # Canonical will support this LTS until April 2027.
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn

      - name: Build Swgjs
        run: yarn build

      - name: E2E Tests
        run: gulp e2e

  unit:
    # Canonical will support this LTS until April 2027.
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install the right version of Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn --ignore-optional

      - name: Unit Tests
        run: gulp unit --headless --coverage

      - uses: codecov/codecov-action@v3
        with:
          files: ./test/coverage/lcov-unit.info
