name: CI

on: [push, pull_request]

jobs:
  check:
    # The Closure JavaScript compiler needs Java 8, and Ubuntu 20.04 LTS has it.
    # Canonical will support this LTS until April 2025.
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          # The Closure JavaScript compiler needs Java 8.
          java-version: '8'

      - name: Install dependencies
        run: yarn

      - name: Check
        run: gulp check

  e2e:
    # The Closure JavaScript compiler needs Java 8, and Ubuntu 20.04 LTS has it.
    # Canonical will support this LTS until April 2025.
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          # The Closure JavaScript compiler needs Java 8.
          java-version: '8'

      - name: Install dependencies
        run: yarn

      - name: E2E Tests
        run: gulp e2e --retries=3

  unit:
    # The Closure JavaScript compiler needs Java 8, and Ubuntu 20.04 LTS has it.
    # Canonical will support this LTS until April 2025.
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          # The Closure JavaScript compiler needs Java 8.
          java-version: '8'

      - name: Install dependencies
        run: yarn

      - name: Unit Tests
        run: gulp unit --headless --coverage

      - uses: codecov/codecov-action@v1
        with:
          file: ./test/coverage/lcov-unit.info
